### PR TITLE
Reset build number to 0

### PR DESCRIPTION
**Pull request by tboggs**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tboggs** [comment]
@lewismc In today's episode of randomly-stabbing-at-things to see if it will fix the license text, I noticed that the feedstock README states

    If the version of a package is being increased, please remember to return the
    build/number back to 0.

I don't know if that just resets the download counter or has some other mysterious effects. Is this worth a try?

**Comment by lewismc** [comment]
@tboggs I thought this was fixed... is there still an issue?

**Comment by tboggs** [comment]
@lewismc Do you see MIT in the description at the bottom of the spectral feedstock page? I still see "GNU General Public License" at the bottom. I'm pretty sure I cleared my browser cache correctly.

https://anaconda.org/conda-forge/spectral

**Comment by lewismc** [comment]
Yes I can see that. Honestly, god knows at this stage what is going on. I'm kinda a bit fed up with this now if I'm honest. There is no string `GNU General Public License` in this feedstock code so as I said god knows where that is coming from. It's beyond me at this stage.

**Comment by tboggs** [comment]
Same here and sorry to keep bugging you about this. I won't worry about the license text. But should the build number be reset to 0?

**Comment by lewismc** [comment]
> Same here and sorry to keep bugging you about this.

No problems at all... the system or process is buggered not you or me :)

> But should the build number be reset to 0?

No I think because I changed the text it should remain at the 1 increment.

**Comment by tboggs** [comment]
Got it. I'll cancel this then. Thanks for you patience!

**Pull request closed without merging**
